name: art
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # File and media
  media_store_plus: 0.1.3
  open_file: ^3.2.1
  file_picker: ^6.1.1
  path_provider: ^2.1.2

  # UI & animations
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  flutter_speed_dial: ^7.0.0
  flutter_animate: ^4.2.0
  animations: ^2.0.7
  dropdown_button2: ^1.0.0
  google_fonts: ^5.1.0
  lucide_icons: ^0.257.0
  fl_chart: ^0.63.0
  fluttertoast: ^8.0.9

  # Printers & Bluetooth
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  esc_pos_utils_plus: ^2.0.1+6
  flutter_bluetooth_serial: ^0.4.0
  blue_thermal_printer: ^1.1.5

  # Utilities
  uuid: ^4.1.0
  permission_handler: ^11.3.0
  csv: ^5.0.0
  provider: ^6.1.2
  collection: ^1.18.0
  connectivity_plus: ^5.0.2
  share_plus: ^7.2.2

  # PDF & Printing
  pdf: ^3.8.4

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl_utils: ^2.8.4
  flutter_launcher_icons: ^0.11.0 # ✅ Added

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png" # ✅ Your icon path here
  min_sdk_android: 21 # Optional: use if minSdk is 21+

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

# fonts:
#   - family: CustomFont
#     fonts:
#       - asset: fonts/CustomFont-Regular.ttf
