// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBJeNKJI-tgCquHQ4gx5f4klogwBXgZe-4",
      authDomain: "artha-71c7e.firebaseapp.com",
      projectId: "artha-71c7e",
      storageBucket: "artha-71c7e.firebasestorage.app",
      messagingSenderId: "165595597250",
      appId: "1:165595597250:web:e086669dd7985907acae5b",
      measurementId: "G-R5XSJZ1FBJ"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpK76MA-5OmwYKLwhoLqsqC8WJAotvpqI',
    appId: '1:165595597250:android:83d92e4c25a28ebfacae5b',
    messagingSenderId: '165595597250',
    projectId: 'artha-71c7e',
    storageBucket: 'artha-71c7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDICJzPZcVocETkk1pdh5EngXYOA5F7ul4',
    appId: '1:165595597250:ios:1d1cb43731ba3d85acae5b',
    messagingSenderId: '165595597250',
    projectId: 'artha-71c7e',
    storageBucket: 'artha-71c7e.firebasestorage.app',
    iosBundleId: 'com.example.art',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDICJzPZcVocETkk1pdh5EngXYOA5F7ul4',
    appId: '1:165595597250:ios:1d1cb43731ba3d85acae5b',
    messagingSenderId: '165595597250',
    projectId: 'artha-71c7e',
    storageBucket: 'artha-71c7e.firebasestorage.app',
    iosBundleId: 'com.example.art',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJeNKJI-tgCquHQ4gx5f4klogwBXgZe-4',
    appId: '1:165595597250:web:e47d3e7e7b654397acae5b',
    messagingSenderId: '165595597250',
    projectId: 'artha-71c7e',
    authDomain: 'artha-71c7e.firebaseapp.com',
    storageBucket: 'artha-71c7e.firebasestorage.app',
    measurementId: 'G-ZGDHTXHZRQ',
  );
}
